export const queryKeys = {
  auth: ['auth'] as const,
  home: ['home'] as const,
  dashboard: (from?: string, to?: string) => ['dashboard', from ?? '', to ?? ''] as const,
  categories: ['categories'] as const,
  products: ['products'] as const,
  product: (idOrSlug: string) => ['products', idOrSlug] as const,
  storeProducts: ['store', 'products'] as const,
  cart: ['cart'] as const,
  cartSummary: ['cart', 'summary'] as const,
  wishlist: ['wishlist'] as const,
  orders: ['orders'] as const,
  order: (orderId: string) => ['orders', orderId] as const,
  payments: (orderId: string) => ['payments', orderId] as const,
  invoices: (invoiceId: string) => ['invoices', invoiceId] as const,
  me: ['me'] as const,
  staffAccounts: ['admin', 'staff-accounts'] as const,
  customerAccounts: ['admin', 'customer-accounts'] as const,
};
